#!/bin/bash

##SBATCH --job-name rsqwin
#SBATCH --time 20:00:00
#SBATCH --account=nmayhall_group
##SBATCH --account=personal
##SBATCH --account=nmayhall_group-paid
##SBATCH --nodes=1
#SBATCH --partition normal_q
#SBATCH --cpus-per-task=1
#SBATCH --mem=4G
##SBATCH --exclusive

MODULE=$(basename $(pwd))
SCRIPT="
    using $MODULE;
    jobdir = ARGS[1];
    load!(jobdir);
    include(\"\$jobdir/script.jl\");
"

WALLTIME=$(squeue -h -j $SLURM_JOB_ID -o "%l")  # GIVES WALLTIME IN hh::mm:ss FORMAT

# LOAD MODULES
sleep 2                                         # GIVE TINKERCLIFFS A MOMENT TO WAKE UP
module reset                                    # Not sure this is necessary..?
module load Julia/1.9.3-linux-x86_64            # LOAD JULIA

# PREPARE PATHS
PROJDIR=$(pwd)                                  # MASTER DIRECTORY WHERE WE SAVE ALL JOBS
JOBDIR=$1                                       # SUB-DIRECTORY TO STORE THIS JOB
OUTFILE="${JOBDIR}/out-${SLURM_JOB_ID}.out"     # STANDARD OUTPUT FOR THE SCRIPT

# SET UP SHOP IN SCRATCH DIRECTORY
rsync -Ra $JOBDIR $TMPDIR                       # TRANSFER FILES TO SCRATCH SPACE
cd $TMPDIR                                      # MOVE INTO THE NEW PLACE

# ASK A DAEMON TO UPDATE HOME DIRECTORY EVERY 5 MINUTES
exec -a "copycat $JOBDIR" bash -c "while true
    do rsync -Ra $JOBDIR $PROJDIR
    sleep 300
done" &
COPYCAT=$!      # REMEMBER THE PID OF OUR COPYCAT, SO WE CAN EUTHANISE IT AT THE END

# RUN JOB - Force-stop it one minute early to guarantee we have time to clean up.
SECONDS=$(echo $WALLTIME | awk -F: '{ print ($1 * 3600) + ($2 * 60) + $3 }')
                                                # CONVERTS WALLTIME TO SECONDS
timeout $(($SECONDS-60)) julia --project="$PROJDIR" -e "$SCRIPT" "$@" >& $OUTFILE
                                                # RUNS THE JULIA SCRIPT

# CLEAN UP
rsync -Ra $JOBDIR $PROJDIR                      # TRANSFER FILES TO HOME ONE LAST TIME
kill $COPYCAT                                   # END THE COPYTCAT DAEMON
wait $COPYCAT 2>/dev/null                           # SUPPRESS OUTPUT FROM THE `kill`
rm -r $JOBDIR                                   # FREE UP SPACE ON SCRATCH

cd $PROJDIR                                     # RETURN HOME
mv "slurm-${SLURM_JOB_ID}.out" $JOBDIR          # MOVE SLURM OUTPUT INTO JOB DIRECTORY
rm "$JOBDIR/running"                            # MARK THE JOB AS COMPLETE

exit

