#!/bin/bash

######################
# This file is super-specific. It works from my desktop computer and none other.
#
# Usage: ./pulljob jobdir
#
# `jobdir` should omit the "jobs" path; it's automatically input.
#  Despite the documentation, it can be any directory, even one containing many jobs,
#       as long as it can be found within the `jobs` directory on ARC.


MODULE=$(basename $(pwd))
source ~/.zshrc     # LOAD ARC_HOME VARIABLE
scp -rq "$ARC_HOME/CtrlJobs/$MODULE/jobs/$1" ./jobs